# Generated by Django 5.2.1 on 2025-08-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_application_link_remove_job_posted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
