# Generated by Django 5.2.1 on 2025-06-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_events', '0002_event_created_by_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
