# Generated by Django 5.2.1 on 2025-06-17 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='location',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='alumni',
            name='graduation_year',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='current_position',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
